services:
  ui:
    image: ${DOCKER_REGISTRY-}ui
    build:
      context: .
      dockerfile: ui/messages/Dockerfile
    ports:
      - "4200:4200"
    networks:
      - app-network
    depends_on:
      - api
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - app-network
    depends_on:
      - kafka
  kafka:
    image: apache/kafka:latest
    container_name: kafka
    environment:
        KAFKA_PROCESS_ROLES: broker,controller
        KAFKA_NODE_ID: 1
        KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
        KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,EXTERNAL://0.0.0.0:9094
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
        KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
        KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
        KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    ports:
        - "9092:9092"
        - "9093:9093"
        - "9094:9094"
    networks:
      - app-network
      
networks:
  app-network:
    driver: bridge